# Generated by Django 2.2.19 on 2022-02-23 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
    ]
